### PR TITLE
Sdk v2 upgrade

### PR DESCRIPTION
**Pull request by dev-codesymphony**
Sdk v2 upgrade

### CODE REVIEW

**Review by imagekitio — CHANGES_REQUESTED** [review]
Sample app should be moved to [quick start repo](https://github.com/imagekit-samples/quickstart). Readme.md should be updated as well.

**Review by imagekitio — CHANGES_REQUESTED** [review]
We should restructure all test cases related code and put it inside `tests` folder as per React. We should not keep it in `src` folder.
image

**Comment by ngyongzhen** [comment]
> Sample app should be moved to [quick start repo](https://github.com/imagekit-samples/quickstart). Readme.md should be updated as well.

Resolved

**Comment by imagekitio** [comment]
> > Sample app should be moved to [quick start repo](https://github.com/imagekit-samples/quickstart). Readme.md should be updated as well.
> 
> Resolved

Where is the PR?

**Comment by imagekitio** [comment]
> We should restructure all test cases related code and put it inside `tests` folder as per React. We should not keep it in `src` folder. image

Not resolved

**Comment by ngyongzhen** [comment]
> > We should restructure all test cases related code and put it inside `tests` folder as per React. We should not keep it in `src` folder. image
> 
> Not resolved

I took out the tests from `src` and put them all into `tests` folder under - what is the expectation?

**Pull request merged**
